name: CI-CD

on:
  pull_request:
    branches:
      - dev
      - pre-release
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - pre-release
      db_operation:
        description: 'Database operation to perform'
        required: false
        type: choice
        options:
          - backup
          - test
          - restore

env:
  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.16-8/x64
  MAVEN_OPTS: -Xmx2G
  SETTINGS_FILE: ./.gitlab-ci-templates/ci-settings.xml
  ATLAS_OPTS: -Dmaven.repo.local=/home/runner/work/jira-apps-bi-core/.m2/repository
  GITLAB_MAVEN_TOKEN: ${{ secrets.GITLAB_MAVEN_TOKEN }}

##############################################################################################################
### Setup Environment
##############################################################################################################

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      ENV_NAME: ${{ steps.setenv.outputs.ENV_NAME }}
    steps:
      - id: setenv
        env:
          DISPATCH_ENV: ${{ github.event.inputs.environment || '' }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_BASE_REF_NAME: ${{ github.base_ref }}
        run: |
          echo "Determining environment and image name..."
          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            ENV_NAME="$DISPATCH_ENV"
          elif [[ "$GITHUB_BASE_REF_NAME" == "dev"  || "$GITHUB_REF_NAME" == "dev" ]]; then
            ENV_NAME=dev
          elif [[ "$GITHUB_BASE_REF_NAME" == "pre-release" || "$GITHUB_REF_NAME" == "pre-release" ]]; then
            ENV_NAME=pre-release
          elif [[ "$GITHUB_REF" == refs/tags/* || "$GITHUB_BASE_REF_NAME" == "master" || "$GITHUB_REF_NAME" == "master" ]]; then
            ENV_NAME=prod
          else
            ENV_NAME=dev
          fi
          echo "ENV_NAME=$ENV_NAME"
          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_OUTPUT

##############################################################################################################
### Code Checks (Frontend + Sonar)
##############################################################################################################

  frontend-check:
    name: frontend-check-${{ needs.set-environment.outputs.ENV_NAME }}
    needs: [set-environment]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
      (github.base_ref == 'dev' || github.base_ref == 'pre-release' || github.base_ref == 'master'))
    steps:
      - uses: actions/checkout@v4

  sonarcloud-check:
    name: sonarcloud-check-${{ needs.set-environment.outputs.ENV_NAME }}
    needs: [set-environment, frontend-check]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
      (github.base_ref == 'dev' || github.base_ref == 'pre-release' || github.base_ref == 'master'))
    steps:
      - uses: actions/checkout@v4

##############################################################################################################
### Dependency Check
##############################################################################################################

  dependencies-check:
    name: dependencies-check-${{ needs.set-environment.outputs.ENV_NAME }}
    needs: [set-environment]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

##############################################################################################################
### Integration Tests (DBs)
##############################################################################################################

  h2-database-integration:
    name: h2-db-integration-check
    needs: [set-environment, sonarcloud-check]
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' &&
        (github.ref_name == 'dev' || github.ref_name == 'pre-release' || github.ref_name == 'master')) ||
      (github.event_name == 'pull_request' &&
        (github.base_ref == 'dev' || github.base_ref == 'pre-release' || github.base_ref == 'master'))
    steps:
      - uses: actions/checkout@v4

  mysql-database-integration:
    name: mysql-db-integration-check
    needs: [set-environment, sonarcloud-check]
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' &&
        (github.ref_name == 'dev' || github.ref_name == 'pre-release' || github.ref_name == 'master')) ||
      (github.event_name == 'pull_request' &&
        (github.base_ref == 'dev' || github.base_ref == 'pre-release' || github.base_ref == 'master'))
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

  mssql-database-integration:
    name: mssql-db-integration-check
    needs: [set-environment, sonarcloud-check]
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' &&
        (github.ref_name == 'dev' || github.ref_name == 'pre-release' || github.ref_name == 'master')) ||
      (github.event_name == 'pull_request' &&
        (github.base_ref == 'dev' || github.base_ref == 'pre-release' || github.base_ref == 'master'))
    steps:
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

  oracle-database-integration:
    name: oracle-db-integration-check
    needs: [set-environment, sonarcloud-check]
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' &&
        (github.ref_name == 'dev' || github.ref_name == 'pre-release' || github.ref_name == 'master')) ||
      (github.event_name == 'pull_request' &&
        (github.base_ref == 'dev' || github.base_ref == 'pre-release' || github.base_ref == 'master'))
    steps:
      - uses: actions/checkout@v4

  postgres-database-integration:
    name: postgres-db-integration-check
    needs: [set-environment, sonarcloud-check]
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' &&
        (github.ref_name == 'dev' || github.ref_name == 'pre-release' || github.ref_name == 'master')) ||
      (github.event_name == 'pull_request' &&
        (github.base_ref == 'dev' || github.base_ref == 'pre-release' || github.base_ref == 'master'))
    steps:
      - uses: actions/checkout@v4

##############################################################################################################
### Endpoint & Service Integration
##############################################################################################################

  endpoint-integration-test:
    name: endpoint-integration-test
    needs: [set-environment, h2-database-integration, mysql-database-integration, mssql-database-integration, oracle-database-integration, postgres-database-integration]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

  service-integration-test:
    name: service-integration-test
    needs: [set-environment, h2-database-integration, mysql-database-integration, mssql-database-integration, oracle-database-integration, postgres-database-integration]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

##############################################################################################################
### Update Plugins Version
##############################################################################################################

  update-plugins-version:
    name: update-plugin-version
    needs: [set-environment, service-integration-test, endpoint-integration-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

##############################################################################################################
### Artifact Generation
##############################################################################################################

  generate-artifact:
    name: generate-artifact
    needs: [set-environment, update-plugins-version]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && (github.ref_name == 'dev' || github.ref_name == 'pre-release' || github.ref_name == 'master')
    strategy:
      matrix:
        APP: [powerbi, tableau, bigquery, sql]
    steps:
      - uses: actions/checkout@v4
